import { access, cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { build } from 'esbuild';

const root = dirname(fileURLToPath(import.meta.url));
const source = join(root, 'src');
const output = join(root, 'dist');
const repository = join(root, '..', '..');
const required = ['index.html', 'app.js', 'styles.css'];

const schemaSource = join(repository, 'schemas', '1.0');
const schemaModule = join(source, 'generated-schemas.js');
const validatorModule = join(source, 'generated-validators.js');
const schemaFiles = await walkFiles(schemaSource);
const schemas = [];
for (const file of schemaFiles) {
  if (!file.endsWith('.schema.json')) continue;
  schemas.push(JSON.parse(await readFile(file, 'utf8')));
}
await writeFile(
  schemaModule,
  `// Generated by apps/playground/build.mjs. Do not edit.\nexport default ${JSON.stringify(schemas)};\n`,
  'utf8',
);
const ajv = new Ajv2020({
  allErrors: true,
  code: { source: true, esm: true },
  strict: true,
  strictRequired: false,
  validateFormats: true,
});
addFormats(ajv);
for (const schema of schemas) ajv.addSchema(schema);
const validatorEntries = schemas
  .filter((schema) => typeof schema.$id === 'string')
  .map((schema, index) => ({ id: schema.$id, name: `validateSchema${index}` }));
const standaloneValidators = standaloneCode(
  ajv,
  Object.fromEntries(validatorEntries.map((entry) => [entry.name, entry.id])),
);
await writeFile(
  validatorModule,
  `${standaloneValidators}\nexport const validatorsById = { ${validatorEntries.map((entry) => `${JSON.stringify(entry.id)}: ${entry.name}`).join(', ')} };\n`,
  'utf8',
);

await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
await cp(source, output, { recursive: true });
await build({
  entryPoints: [join(source, 'app.js')],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2022',
  alias: {
    '@paperandslate/eom-authority': join(repository, 'packages', 'authority', 'src', 'index.ts'),
    '@paperandslate/eom-core/ids': join(repository, 'packages', 'core', 'src', 'ids.ts'),
    '@paperandslate/eom-core/json': join(repository, 'packages', 'core', 'src', 'json.ts'),
    '@paperandslate/eom-core/time': join(repository, 'packages', 'core', 'src', 'time.ts'),
  },
  outfile: join(output, 'app.js'),
  legalComments: 'none',
});
for (const file of required) {
  try {
    await access(join(output, file));
  } catch {
    throw new Error(`Playground source is missing required file: ${file}`);
  }
}
await writeFile(
  join(output, 'build-metadata.json'),
  `${JSON.stringify({ name: 'eom-playground', version: '1.0.0-rc.3', generatedBy: 'apps/playground/build.mjs' }, null, 2)}\n`,
  'utf8',
);
process.stdout.write(`built local EOM playground at ${output}\n`);

async function walkFiles(directory) {
  const entries = (await readdir(directory, { withFileTypes: true })).sort((left, right) =>
    left.name < right.name ? -1 : left.name > right.name ? 1 : 0,
  );
  const files = [];
  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await walkFiles(path)));
    else if (entry.isFile()) files.push(path);
  }
  return files;
}
