// @generated by scripts/generate-types.ts; do not edit directly.
// SPDX-License-Identifier: Apache-2.0

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | Readonly<{ [key: string]: JsonValue }> | ReadonlyArray<JsonValue>;

export type CommonAbsoluteUri = string;

export type CommonAddress = Readonly<{
  readonly "accessibilityNotes"?: CommonLocalized;
  readonly "administrativeArea"?: CommonLocalized;
  readonly "countryCode"?: string;
  readonly "dependentLocality"?: CommonLocalized;
  readonly "effective"?: CommonPeriod;
  readonly "formatted"?: CommonLocalized;
  readonly "geo"?: CommonGeoPoint;
  readonly "lines"?: ReadonlyArray<CommonLocalized>;
  readonly "locality"?: CommonLocalized;
  readonly "postalCode"?: string;
  readonly "public"?: boolean;
  readonly "type"?: string;
}>;

export type CommonAlternate = Readonly<{
  readonly "fidelity"?: "canonical" | "lossless" | "projected" | "human-readable" | "summary";
  readonly "href": CommonHttpsUri;
  readonly "mediaType": string;
  readonly "purpose"?: string;
}>;

export type CommonBcp47 = string;

export type CommonCatalogVersion = Readonly<{
  readonly "effective": CommonPeriod;
  readonly "id": CommonAbsoluteUri;
  readonly "label": CommonLocalized;
  readonly "public"?: boolean;
  readonly "publishedAt"?: CommonDateTime;
  readonly "source"?: CommonAbsoluteUri;
  readonly "status": "draft" | "proposed" | "active" | "historical" | "retired";
}>;

export type CommonDate = string;

export type CommonDateTime = string;

export type CommonEntityRef = Readonly<{
  readonly "id": CommonAbsoluteUri;
  readonly "name"?: CommonLocalized;
  readonly "type"?: string;
}>;

export type CommonExtensions = Readonly<Record<string, JsonValue>>;

export type CommonGeoPoint = Readonly<{
  readonly "accuracyMeters"?: number;
  readonly "altitude"?: number;
  readonly "latitude": number;
  readonly "longitude": number;
}>;

export type CommonHttpsUri = string;

export type CommonIdentifier = Readonly<{
  readonly "authority"?: CommonAbsoluteUri;
  readonly "scheme": string;
  readonly "source"?: CommonAbsoluteUri;
  readonly "validFrom"?: CommonDate | CommonDateTime;
  readonly "validUntil"?: CommonDate | CommonDateTime;
  readonly "value": string;
  readonly "verificationStatus"?: "verified" | "unverified" | "disputed" | "expired";
  readonly "verifiedAt"?: CommonDateTime;
}>;

export type CommonIntegrity = JsonValue | JsonValue;

export type CommonLocalized = string | Readonly<{
  readonly "default": CommonBcp47;
  readonly "directions"?: Readonly<Record<string, JsonValue>>;
  readonly "values": Readonly<Record<string, JsonValue>>;
}>;

export type CommonPeriod = Readonly<{
  readonly "from"?: CommonDate | CommonDateTime;
  readonly "until"?: CommonDate | CommonDateTime;
}>;

export type CommonProvenanceRef = string;

export type CommonPublisher = Readonly<{
  readonly "contact"?: CommonEntityRef;
  readonly "id": CommonAbsoluteUri;
  readonly "identifiers"?: ReadonlyArray<CommonIdentifier>;
  readonly "name": CommonLocalized;
  readonly "statement"?: CommonLocalized;
  readonly "type": string;
  readonly "website"?: CommonHttpsUri;
}>;

export type CommonScope = Readonly<{
  readonly "canonicalOrigins"?: ReadonlyArray<CommonHttpsUri>;
  readonly "excludedPaths"?: ReadonlyArray<string>;
  readonly "jurisdictions"?: ReadonlyArray<string>;
  readonly "origin": CommonHttpsUri;
  readonly "paths"?: ReadonlyArray<string>;
  readonly "scopeStatement"?: CommonLocalized;
}>;

export type Common = JsonValue;

export type ManifestIndexingPolicy = Readonly<{
  readonly "allowArchiving"?: boolean;
  readonly "allowCommercialReuse"?: boolean | null;
  readonly "allowPublicIndexing"?: boolean;
  readonly "corrections"?: CommonHttpsUri;
  readonly "terms"?: CommonHttpsUri;
}>;

export type ManifestNotice = Readonly<{
  readonly "effective"?: CommonPeriod;
  readonly "href"?: CommonHttpsUri;
  readonly "id": CommonAbsoluteUri;
  readonly "message": CommonLocalized;
  readonly "title": CommonLocalized;
}>;

export type ManifestOrganizationSummary = Readonly<{
  readonly "canonicalUrl": CommonHttpsUri;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "identifiers"?: ReadonlyArray<CommonIdentifier>;
  readonly "name": CommonLocalized;
  readonly "parent"?: CommonAbsoluteUri;
  readonly "profile"?: CommonAbsoluteUri;
  readonly "type": string;
}>;

export type Manifest = Readonly<{
  readonly "$schema": "https://paperandslate.org/schemas/eom/1.0/manifest.schema.json";
  readonly "canonical": CommonHttpsUri;
  readonly "capabilities": ReadonlyArray<Capability>;
  readonly "conformance"?: CommonAbsoluteUri;
  readonly "contacts"?: ReadonlyArray<CommonEntityRef>;
  readonly "defaultLanguage"?: CommonBcp47;
  readonly "delegations"?: ReadonlyArray<Delegation>;
  readonly "expires"?: CommonDateTime;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "indexingPolicy"?: ManifestIndexingPolicy;
  readonly "modified"?: CommonDateTime;
  readonly "notices"?: ReadonlyArray<ManifestNotice>;
  readonly "organizationIndex"?: CommonAbsoluteUri;
  readonly "organizations": ReadonlyArray<ManifestOrganizationSummary>;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "publisher": CommonPublisher;
  readonly "resources": ReadonlyArray<Resource>;
  readonly "scope": CommonScope;
  readonly "signing"?: Readonly<{
  readonly "algorithm"?: string;
  readonly "keySet"?: CommonAbsoluteUri;
  readonly "required"?: boolean;
  readonly "signatures"?: ReadonlyArray<CommonHttpsUri>;
}>;
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "supportedLanguages"?: ReadonlyArray<CommonBcp47>;
  readonly "type": "manifest";
  readonly "version": "1.0";
}>;

export type Resource = Readonly<{
  readonly "accessPolicy"?: "public" | "public-with-terms" | "restricted" | "retired";
  readonly "alternates"?: ReadonlyArray<CommonAlternate>;
  readonly "authority"?: Readonly<{
  readonly "delegation": CommonAbsoluteUri;
  readonly "origin"?: CommonHttpsUri;
}>;
  readonly "description"?: CommonLocalized;
  readonly "effective"?: CommonPeriod;
  readonly "expires"?: CommonDateTime;
  readonly "extensions"?: CommonExtensions;
  readonly "href": CommonHttpsUri;
  readonly "id": CommonAbsoluteUri;
  readonly "integrity"?: CommonIntegrity;
  readonly "languages"?: ReadonlyArray<CommonBcp47>;
  readonly "license"?: CommonAbsoluteUri;
  readonly "mediaType": string;
  readonly "modified"?: CommonDateTime;
  readonly "profile"?: CommonAbsoluteUri;
  readonly "schema"?: CommonAbsoluteUri;
  readonly "subjects": ReadonlyArray<CommonAbsoluteUri>;
  readonly "title"?: CommonLocalized;
  readonly "type": string;
  readonly "version": string;
}>;

export type Capability = Readonly<{
  readonly "description"?: CommonLocalized;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "profile"?: CommonAbsoluteUri;
  readonly "resources"?: ReadonlyArray<CommonAbsoluteUri>;
  readonly "status": "active" | "experimental" | "deprecated" | "retired";
  readonly "version": string;
}>;

export type Delegation = Readonly<{
  readonly "delegate": CommonHttpsUri | Readonly<{
  readonly "id": CommonAbsoluteUri;
  readonly "name": CommonLocalized;
  readonly "type"?: string;
  readonly "website"?: CommonHttpsUri;
}>;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "keys"?: ReadonlyArray<CommonAbsoluteUri>;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "revokedAt"?: CommonDateTime;
  readonly "scope": JsonValue | JsonValue | JsonValue | JsonValue;
  readonly "statement"?: CommonLocalized;
  readonly "status": "active" | "revoked" | "expired";
  readonly "subject"?: CommonAbsoluteUri;
  readonly "successor"?: CommonAbsoluteUri;
  readonly "transitive": false;
  readonly "type"?: "delegation";
  readonly "validFrom": CommonDateTime;
  readonly "validUntil"?: CommonDateTime;
}>;

export type Provenance = Readonly<{
  readonly "assertedBy"?: CommonAbsoluteUri;
  readonly "confidence"?: number;
  readonly "contentDigest"?: string;
  readonly "effective"?: CommonPeriod;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "license"?: CommonAbsoluteUri;
  readonly "method"?: string;
  readonly "notes"?: CommonLocalized;
  readonly "observedAt": CommonDateTime;
  readonly "retrievedAt"?: CommonDateTime;
  readonly "scope": "resource" | "object" | "field";
  readonly "source": Readonly<{
  readonly "license"?: CommonAbsoluteUri;
  readonly "publisher"?: CommonEntityRef;
  readonly "type": "organization-publication" | "organization-website" | "organization-api" | "government-registry" | "government-statistical-dataset" | "standards-body" | "vendor-authorized-feed" | "human-submission" | "agent-extraction" | "foundation-derived" | "mirror" | "unknown" | "official-website" | "official-document" | "public-dataset" | "government-record" | "partner-feed" | "human-review" | "inference" | "other";
  readonly "uri": CommonAbsoluteUri;
}>;
  readonly "targetObjectId"?: CommonAbsoluteUri;
  readonly "targetPointers"?: ReadonlyArray<string>;
  readonly "targetResource"?: CommonAbsoluteUri;
  readonly "transformation"?: string;
  readonly "type"?: "provenance";
  readonly "verification"?: "unverified" | "automated" | "human-reviewed" | "publisher-confirmed" | "disputed";
  readonly "verificationStatus"?: "asserted" | "extracted" | "reviewed" | "verified-against-source" | "disputed" | "stale" | "withdrawn";
}>;

export type Source = Readonly<{
  readonly "accessRestrictions"?: "public" | "operator-approved" | "restricted" | "unknown";
  readonly "contentDigest"?: string;
  readonly "effective"?: CommonPeriod;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "jurisdiction"?: string;
  readonly "license"?: CommonAbsoluteUri;
  readonly "licenseStatus"?: "permitted" | "review-required" | "restricted" | "unknown";
  readonly "modules"?: ReadonlyArray<string>;
  readonly "notes"?: CommonLocalized;
  readonly "observedAt"?: CommonDateTime;
  readonly "publisher"?: CommonEntityRef;
  readonly "retrievedAt": CommonDateTime;
  readonly "reviewOwner"?: string;
  readonly "snapshot"?: Readonly<{
  readonly "digest": string;
  readonly "kind": "digest-only" | "local-copy" | "controlled-fixture";
  readonly "path"?: string;
  readonly "retentionUntil"?: CommonDateTime;
}>;
  readonly "sourceType": "organization-publication" | "organization-website" | "organization-api" | "government-registry" | "government-statistical-dataset" | "standards-body" | "vendor-authorized-feed" | "human-submission" | "agent-extraction" | "foundation-derived" | "mirror" | "unknown";
  readonly "status"?: "discovered" | "approved" | "rejected" | "stale" | "withdrawn";
  readonly "title": CommonLocalized;
  readonly "type": "source-record";
  readonly "uri": CommonAbsoluteUri;
}>;

export type Evidence = Readonly<{
  readonly "ambiguity"?: string;
  readonly "authorityClass": "government-identity" | "organization-origin" | "governing-body" | "government-dataset" | "authorized-vendor" | "foundation-derived" | "third-party" | "unknown";
  readonly "confidence": number;
  readonly "evidence": Readonly<{
  readonly "contentDigest"?: string;
  readonly "effective"?: CommonPeriod;
  readonly "excerpt"?: string;
  readonly "observedAt": CommonDateTime;
}>;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "method": Readonly<{
  readonly "agent"?: string;
  readonly "kind": "direct-extraction" | "normalize" | "mapping" | "inference" | "human-input";
  readonly "modelVersion"?: string;
  readonly "promptVersion"?: string;
  readonly "transformation"?: string;
}>;
  readonly "originalValue"?: JsonValue;
  readonly "privacyClass": "public-reviewed" | "public-review-required" | "personal-data" | "sensitive-data" | "quarantined";
  readonly "proposedValue": JsonValue;
  readonly "review": Readonly<{
  readonly "notes"?: string;
  readonly "requiredOwner": string;
  readonly "reviewedAt"?: CommonDateTime;
  readonly "reviewedBy"?: string;
  readonly "state": "pending" | "changes-requested" | "approved" | "rejected" | "quarantined";
}>;
  readonly "source": Readonly<{
  readonly "locator": JsonValue | JsonValue | JsonValue | JsonValue | JsonValue | JsonValue;
  readonly "sourceId": CommonAbsoluteUri;
}>;
  readonly "target": Readonly<{
  readonly "pointer": string;
  readonly "resourceId": CommonAbsoluteUri;
}>;
  readonly "transformation"?: string;
  readonly "type": "claim-record";
}>;

export type Conflict = Readonly<{
  readonly "claims": ReadonlyArray<Readonly<{
  readonly "claimId": CommonAbsoluteUri;
  readonly "observedAt"?: CommonDateTime;
  readonly "provenance": CommonAbsoluteUri;
  readonly "value": JsonValue;
}>>;
  readonly "conflictType"?: "direct-disagreement" | "effective-date-mismatch" | "unit-mismatch" | "stale-source" | "naming-variation" | "identifier-collision" | "scope-mismatch" | "translation-disagreement" | "inferred-relationship";
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "materiality"?: "low" | "medium" | "high";
  readonly "precedenceExplanation"?: string;
  readonly "reason": string;
  readonly "recommendedClaimId"?: CommonAbsoluteUri;
  readonly "resolution"?: Readonly<{
  readonly "decidedAt": CommonDateTime;
  readonly "followUp"?: string;
  readonly "rationale": string;
  readonly "selectedClaimId": CommonAbsoluteUri;
}>;
  readonly "reviewer"?: string;
  readonly "status": "unresolved" | "resolved" | "withdrawn";
  readonly "target": Readonly<{
  readonly "pointer": string;
  readonly "resourceId": CommonAbsoluteUri;
}>;
  readonly "type": "conflict-record";
}>;

export type Review = Readonly<{
  readonly "claimId": CommonAbsoluteUri;
  readonly "conflictsConsidered"?: ReadonlyArray<CommonAbsoluteUri>;
  readonly "decision": "approved" | "rejected" | "modified" | "deferred";
  readonly "extensions"?: CommonExtensions;
  readonly "followUp"?: string;
  readonly "id": CommonAbsoluteUri;
  readonly "rationale": string;
  readonly "reviewAgainAt"?: CommonDateTime;
  readonly "reviewer": string;
  readonly "selectedValue"?: JsonValue;
  readonly "timestamp": CommonDateTime;
  readonly "type": "review-decision";
}>;

export type Candidate = Readonly<{
  readonly "claims": ReadonlyArray<CommonAbsoluteUri>;
  readonly "conflicts"?: ReadonlyArray<CommonAbsoluteUri>;
  readonly "createdAt": CommonDateTime;
  readonly "directPublication": false;
  readonly "extensions"?: CommonExtensions;
  readonly "generatedPreview"?: string;
  readonly "id": CommonAbsoluteUri;
  readonly "notes"?: string;
  readonly "privacyReview"?: "pending" | "clear" | "blocked" | "quarantined";
  readonly "requiredOwners"?: ReadonlyArray<string>;
  readonly "sourceSet": ReadonlyArray<CommonAbsoluteUri>;
  readonly "status": "discovered" | "extracted" | "normalized" | "validation-failed" | "review-ready" | "changes-requested" | "approved" | "generated" | "release-approved" | "published" | "superseded";
  readonly "type": "candidate-workspace";
  readonly "updatedAt"?: CommonDateTime;
}>;

export type Signature = Readonly<{
  readonly "$schema": "https://paperandslate.org/schemas/eom/1.0/signature.schema.json";
  readonly "algorithm": "EdDSA";
  readonly "canonical": CommonHttpsUri;
  readonly "canonicalization": "RFC8785-JCS";
  readonly "compact": string;
  readonly "contentType"?: "application/json";
  readonly "createdAt": CommonDateTime;
  readonly "detached": true;
  readonly "expires"?: CommonDateTime;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "keyId": CommonAbsoluteUri;
  readonly "payloadDigest": string;
  readonly "protected": string;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "signature": string;
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "subject": CommonAbsoluteUri;
  readonly "type": "signature";
  readonly "version": "1.0";
}>;

export type Mapping = Readonly<{
  readonly "mappings": ReadonlyArray<Readonly<{
  readonly "certificationClaim": false;
  readonly "direction": "import" | "export" | "bidirectional";
  readonly "fixture"?: string;
  readonly "id": CommonAbsoluteUri;
  readonly "lossiness": Readonly<{
  readonly "approximate": ReadonlyArray<string>;
  readonly "exact": ReadonlyArray<string>;
  readonly "omitted": ReadonlyArray<string>;
}>;
  readonly "maintainer"?: string;
  readonly "modules": ReadonlyArray<string>;
  readonly "notes"?: string;
  readonly "privacy": Readonly<{
  readonly "allowlist": ReadonlyArray<string>;
  readonly "prohibitedFields": ReadonlyArray<string>;
  readonly "reviewRequired": boolean;
}>;
  readonly "provenance": "claim-ledger" | "source-digest-only";
  readonly "publicFieldAllowlist": ReadonlyArray<string>;
  readonly "reviewedAt"?: CommonDateTime;
  readonly "sourceFormat": string;
  readonly "sourceVersion": string;
  readonly "status": "experimental" | "preview" | "stable" | "deprecated";
  readonly "targetFormat": "eom-authoring-candidate";
  readonly "transformations": ReadonlyArray<string>;
  readonly "version": string;
}>>;
  readonly "type": "mapping-registry";
  readonly "version": "1.0";
}>;

export type ModuleRegistryModule = Readonly<{
  readonly "changeController": CommonAbsoluteUri;
  readonly "collection": "single" | "items" | "paged" | "delegated";
  readonly "compatibleProtocolVersions": ReadonlyArray<string>;
  readonly "conformanceProfile": CommonAbsoluteUri;
  readonly "currentVersion": string;
  readonly "description": CommonLocalized;
  readonly "example": string;
  readonly "extensionPoints": ReadonlyArray<CommonAbsoluteUri>;
  readonly "freshness": string;
  readonly "lastReviewed": CommonDate;
  readonly "mappings": ReadonlyArray<string>;
  readonly "moduleUri": CommonAbsoluteUri;
  readonly "privacyClass": string;
  readonly "resourceType": string;
  readonly "schema": CommonHttpsUri;
  readonly "shortName": string;
  readonly "status": "working-draft" | "stable" | "experimental" | "deprecated";
  readonly "title": CommonLocalized;
}>;

export type ModuleRegistry = Readonly<{
  readonly "$schema": "https://paperandslate.org/schemas/eom/1.0/module-registry.schema.json";
  readonly "canonical": CommonHttpsUri;
  readonly "changeController": CommonAbsoluteUri;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "lastReviewed": CommonDate;
  readonly "modules": ReadonlyArray<ModuleRegistryModule>;
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "status": "working-draft" | "registered" | "deprecated";
  readonly "type": "module-registry";
  readonly "version": "1.0";
}>;

export type VocabularyRegistryVocabulary = Readonly<{
  readonly "category": string;
  readonly "compatibleProtocolVersions": ReadonlyArray<string>;
  readonly "controller": CommonAbsoluteUri;
  readonly "currentVersion": string;
  readonly "description": CommonLocalized;
  readonly "lastReviewed": CommonDate;
  readonly "mappings": ReadonlyArray<string>;
  readonly "openness": "open" | "closed" | "extensible";
  readonly "schema": CommonHttpsUri;
  readonly "snapshot": CommonHttpsUri;
  readonly "status": "working-draft" | "stable" | "experimental" | "deprecated";
  readonly "title": CommonLocalized;
  readonly "vocabularyUri": CommonAbsoluteUri;
}>;

export type VocabularyRegistry = Readonly<{
  readonly "$schema": "https://paperandslate.org/schemas/eom/1.0/vocabulary-registry.schema.json";
  readonly "canonical": CommonHttpsUri;
  readonly "changeController": CommonAbsoluteUri;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "lastReviewed": CommonDate;
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "status": "working-draft" | "registered" | "deprecated";
  readonly "type": "vocabulary-registry";
  readonly "version": "1.0";
  readonly "vocabularies": ReadonlyArray<VocabularyRegistryVocabulary>;
}>;

export type VocabularyMapping = Readonly<{
  readonly "confidence": "high" | "medium" | "low" | "unreviewed";
  readonly "evidence"?: string;
  readonly "relation": "exactMatch" | "closeMatch" | "broaderMatch" | "narrowerMatch" | "relatedMatch" | "supersedes" | "approximateEquivalent";
  readonly "target": CommonAbsoluteUri;
}>;

export type VocabularyTerm = Readonly<{
  readonly "broader"?: ReadonlyArray<CommonAbsoluteUri>;
  readonly "changeNote"?: CommonLocalized;
  readonly "code": string;
  readonly "definition": CommonLocalized;
  readonly "effective"?: CommonPeriod;
  readonly "jurisdiction"?: string;
  readonly "license"?: string;
  readonly "mappings"?: ReadonlyArray<VocabularyMapping>;
  readonly "narrower"?: ReadonlyArray<CommonAbsoluteUri>;
  readonly "preferredLabel": CommonLocalized;
  readonly "related"?: ReadonlyArray<CommonAbsoluteUri>;
  readonly "source"?: CommonAbsoluteUri;
  readonly "status": "active" | "deprecated" | "proposed";
  readonly "uri": CommonAbsoluteUri;
}>;

export type Vocabulary = Readonly<{
  readonly "$schema": "https://paperandslate.org/schemas/eom/1.0/vocabulary.schema.json";
  readonly "canonical": CommonHttpsUri;
  readonly "category": string;
  readonly "compatibleProtocolVersions"?: ReadonlyArray<string>;
  readonly "contentDigest": string;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "license": string;
  readonly "openness": "open" | "closed" | "extensible";
  readonly "retrievedAt": CommonDateTime;
  readonly "source": CommonAbsoluteUri;
  readonly "sourceVersion"?: string;
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "terms": ReadonlyArray<VocabularyTerm>;
  readonly "transformation"?: CommonLocalized;
  readonly "type": "vocabulary";
  readonly "updateMechanism"?: string;
  readonly "version": "1.0";
}>;

export type ConformanceProfile = Readonly<{
  readonly "$schema": "https://paperandslate.org/schemas/eom/1.0/conformance-profile.schema.json";
  readonly "canonical": CommonHttpsUri;
  readonly "description": CommonLocalized;
  readonly "extensions"?: CommonExtensions;
  readonly "externalEvidenceRequired"?: boolean;
  readonly "id": CommonAbsoluteUri;
  readonly "lastReviewed": CommonDate;
  readonly "modes": ReadonlyArray<"fixture" | "publisher" | "consumer" | "generator">;
  readonly "requiredChecks"?: ReadonlyArray<string>;
  readonly "requirements": ReadonlyArray<string>;
  readonly "role": "publisher" | "consumer" | "generator" | "validator" | "module" | "signature";
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "status": "working-draft" | "stable" | "deprecated";
  readonly "type": "conformance-profile";
  readonly "version": "1.0";
}>;

export type ConformanceProfileRegistry = Readonly<{
  readonly "$schema": "https://paperandslate.org/schemas/eom/1.0/conformance-profile-registry.schema.json";
  readonly "canonical": CommonHttpsUri;
  readonly "changeController": CommonAbsoluteUri;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "lastReviewed": CommonDate;
  readonly "profiles": ReadonlyArray<ConformanceProfile>;
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "status": "working-draft" | "registered" | "deprecated";
  readonly "type": "conformance-profile-registry";
  readonly "version": "1.0";
}>;

export type OrganizationProfile = Readonly<{
  readonly "$schema": "https://paperandslate.org/schemas/eom/1.0/organization-profile.schema.json";
  readonly "address"?: CommonAddress;
  readonly "alternateNames"?: ReadonlyArray<CommonLocalized>;
  readonly "campuses"?: ReadonlyArray<CommonEntityRef>;
  readonly "canonical": CommonHttpsUri;
  readonly "children"?: ReadonlyArray<CommonEntityRef>;
  readonly "contacts"?: ReadonlyArray<CommonEntityRef>;
  readonly "defaultLanguage"?: CommonBcp47;
  readonly "departments"?: ReadonlyArray<CommonEntityRef>;
  readonly "description"?: CommonLocalized;
  readonly "expires"?: CommonDateTime;
  readonly "extensions"?: CommonExtensions;
  readonly "founded"?: CommonDate | number;
  readonly "id": CommonAbsoluteUri;
  readonly "identifiers"?: ReadonlyArray<CommonIdentifier>;
  readonly "languages"?: ReadonlyArray<CommonBcp47>;
  readonly "modified"?: CommonDateTime;
  readonly "name": CommonLocalized;
  readonly "organizationType": string;
  readonly "parent"?: CommonEntityRef;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "status"?: "active" | "planned" | "closed" | "merged" | "unknown";
  readonly "supportedLanguages"?: ReadonlyArray<CommonBcp47>;
  readonly "type": "organization-profile";
  readonly "version": "1.0";
  readonly "website"?: CommonHttpsUri;
}>;

export type OrganizationIndex = Readonly<{
  readonly "$schema": "https://paperandslate.org/schemas/eom/1.0/organization-index.schema.json";
  readonly "canonical": CommonHttpsUri;
  readonly "expires"?: CommonDateTime;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "modified"?: CommonDateTime;
  readonly "next"?: CommonHttpsUri;
  readonly "organizations": ReadonlyArray<ManifestOrganizationSummary>;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "type": "organization-index";
  readonly "version": "1.0";
}>;

export type ResourceIndex = Readonly<{
  readonly "$schema": "https://paperandslate.org/schemas/eom/1.0/resource-index.schema.json";
  readonly "canonical": CommonHttpsUri;
  readonly "chunks": ReadonlyArray<Readonly<{
  readonly "count"?: number;
  readonly "digest"?: string;
  readonly "from"?: string;
  readonly "href": CommonHttpsUri;
  readonly "id"?: CommonAbsoluteUri;
  readonly "through"?: string;
}>>;
  readonly "expires"?: CommonDateTime;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "itemType": string;
  readonly "modified"?: CommonDateTime;
  readonly "ordering"?: string;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "snapshotAt"?: CommonDateTime;
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "subject"?: CommonAbsoluteUri;
  readonly "total"?: number;
  readonly "type": "resource-index";
  readonly "version": "1.0";
}>;

export type ContactDirectoryContactPoint = Readonly<{
  readonly "accessibility"?: ReadonlyArray<CommonLocalized>;
  readonly "address"?: CommonAddress;
  readonly "audience"?: ReadonlyArray<string>;
  readonly "department"?: CommonEntityRef;
  readonly "email"?: string;
  readonly "extensions"?: CommonExtensions;
  readonly "hours"?: CommonLocalized;
  readonly "id": CommonAbsoluteUri;
  readonly "languages"?: ReadonlyArray<CommonBcp47>;
  readonly "organization"?: CommonEntityRef;
  readonly "person"?: CommonEntityRef;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "publicationReview"?: Readonly<{
  readonly "expires"?: CommonDateTime;
  readonly "reviewedAt": CommonDateTime;
  readonly "reviewedBy"?: CommonEntityRef;
  readonly "status": "approved" | "pending" | "withdrawn" | "expired";
}>;
  readonly "role": CommonLocalized;
  readonly "telephone"?: string;
  readonly "type": "contact-point";
  readonly "website"?: CommonHttpsUri;
}>;

export type ContactDirectory = Readonly<{
  readonly "$schema": "https://paperandslate.org/schemas/eom/1.0/contact-directory.schema.json";
  readonly "canonical": CommonHttpsUri;
  readonly "contacts": ReadonlyArray<ContactDirectoryContactPoint>;
  readonly "defaultLanguage"?: CommonBcp47;
  readonly "expires"?: CommonDateTime;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "modified"?: CommonDateTime;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "subject": CommonAbsoluteUri;
  readonly "supportedLanguages"?: ReadonlyArray<CommonBcp47>;
  readonly "type": "contact-directory";
  readonly "version": "1.0";
}>;

export type KeySet = Readonly<{
  readonly "$schema": "https://paperandslate.org/schemas/eom/1.0/key-set.schema.json";
  readonly "canonical": CommonHttpsUri;
  readonly "expires"?: CommonDateTime;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "keys": ReadonlyArray<Readonly<{
  readonly "alg"?: "EdDSA";
  readonly "kid": CommonAbsoluteUri;
  readonly "kty": string;
  readonly "owner"?: CommonAbsoluteUri;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "publicKeyJwk"?: Readonly<{
  readonly "crv": "Ed25519";
  readonly "kty": "OKP";
  readonly "x": string;
}>;
  readonly "purpose"?: string;
  readonly "revokedAt"?: CommonDateTime;
  readonly "scope"?: Readonly<{
  readonly "resourceIds"?: ReadonlyArray<CommonAbsoluteUri>;
  readonly "resourceTypes"?: ReadonlyArray<string>;
}>;
  readonly "status": "active" | "revoked" | "expired";
  readonly "successor"?: CommonAbsoluteUri;
  readonly "use": "sig";
  readonly "validFrom"?: CommonDateTime;
  readonly "validUntil"?: CommonDateTime;
}>>;
  readonly "modified"?: CommonDateTime;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "type": "key-set";
  readonly "version": "1.0";
}>;

export type ConformanceReport = Readonly<{
  readonly "$schema": "https://paperandslate.org/schemas/eom/1.0/conformance-report.schema.json";
  readonly "canonical": CommonHttpsUri;
  readonly "checks": ReadonlyArray<Readonly<{
  readonly "evidence"?: ReadonlyArray<CommonAbsoluteUri>;
  readonly "id": CommonAbsoluteUri;
  readonly "message"?: CommonLocalized;
  readonly "status": "pass" | "fail" | "skip" | "warn";
}>>;
  readonly "expires"?: CommonDateTime;
  readonly "extensions"?: CommonExtensions;
  readonly "generatedAt"?: CommonDateTime;
  readonly "id": CommonAbsoluteUri;
  readonly "implementation": Readonly<{
  readonly "name": string;
  readonly "source"?: CommonHttpsUri;
  readonly "version": string;
}>;
  readonly "modified"?: CommonDateTime;
  readonly "profile"?: CommonAbsoluteUri;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "status": "conforming" | "partial" | "non-conforming";
  readonly "type": "conformance-report";
  readonly "version": "1.0";
}>;

export type ModuleResource = Readonly<{
  readonly "$schema": string;
  readonly "canonical": CommonHttpsUri;
  readonly "catalogVersion"?: CommonCatalogVersion;
  readonly "defaultLanguage"?: CommonBcp47;
  readonly "description"?: CommonLocalized;
  readonly "effective"?: CommonPeriod;
  readonly "expires"?: CommonDateTime;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "items": ReadonlyArray<Readonly<Record<string, JsonValue>>>;
  readonly "license"?: CommonAbsoluteUri;
  readonly "modified"?: CommonDateTime;
  readonly "next"?: CommonHttpsUri;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "publisher"?: CommonPublisher;
  readonly "releaseStatus"?: "draft" | "proposed" | "active" | "historical" | "retired";
  readonly "specification": "https://paperandslate.org/spec/eom/1.0";
  readonly "subjects": ReadonlyArray<CommonAbsoluteUri>;
  readonly "supportedLanguages"?: ReadonlyArray<CommonBcp47>;
  readonly "title"?: CommonLocalized;
  readonly "type": string;
  readonly "version": "1.0";
}>;

export type ModuleItemsAcademicCalendar = Readonly<Record<string, JsonValue>>;

export type ModuleItemsAcademicPeriod = Readonly<{
  readonly "end": CommonDate;
  readonly "id": CommonAbsoluteUri;
  readonly "name": CommonLocalized;
  readonly "order"?: number;
  readonly "start": CommonDate;
  readonly "type": string;
}>;

export type ModuleItemsAdmissions = Readonly<Record<string, JsonValue>>;

export type ModuleItemsAgeRange = Readonly<{
  readonly "approximate"?: boolean;
  readonly "maximum"?: number;
  readonly "maximumInclusive"?: boolean;
  readonly "minimum"?: number;
  readonly "minimumInclusive"?: boolean;
  readonly "unit"?: "years" | "months";
}>;

export type ModuleItemsApiReference = Readonly<Record<string, JsonValue>>;

export type ModuleItemsApplicationWindow = Readonly<{
  readonly "for"?: CommonLocalized;
  readonly "from": CommonDate;
  readonly "until": CommonDate;
}>;

export type ModuleItemsAvailability = Readonly<{
  readonly "enrollmentUrl"?: CommonHttpsUri;
  readonly "expires": CommonDateTime;
  readonly "observedAt": CommonDateTime;
  readonly "seatsRemaining"?: number;
  readonly "source"?: CommonAbsoluteUri;
  readonly "status": "open" | "waitlist" | "full" | "closed" | "unknown";
}>;

export type ModuleItemsCalendarDay = Readonly<{
  readonly "classification": string;
  readonly "date": CommonDate;
  readonly "label"?: CommonLocalized;
}>;

export type ModuleItemsCampus = Readonly<Record<string, JsonValue>>;

export type ModuleItemsClub = Readonly<Record<string, JsonValue>>;

export type ModuleItemsCourse = Readonly<Record<string, JsonValue>>;

export type ModuleItemsCourseDelivery = Readonly<{
  readonly "accessibilityFeatures"?: ReadonlyArray<CommonLocalized>;
  readonly "campuses"?: ReadonlyArray<CommonEntityRef>;
  readonly "fieldTripNotes"?: CommonLocalized;
  readonly "languages"?: ReadonlyArray<CommonBcp47>;
  readonly "locations"?: ReadonlyArray<CommonEntityRef>;
  readonly "modes"?: ReadonlyArray<string>;
}>;

export type ModuleItemsCourseRelationships = Readonly<{
  readonly "crossListedAs"?: ReadonlyArray<CommonEntityRef>;
  readonly "equivalent"?: ReadonlyArray<CommonEntityRef>;
  readonly "partOfProgram"?: ReadonlyArray<CommonEntityRef>;
  readonly "recommendedAfter"?: ReadonlyArray<CommonEntityRef>;
  readonly "recommendedBefore"?: ReadonlyArray<CommonEntityRef>;
  readonly "replacedBy"?: ReadonlyArray<CommonEntityRef>;
  readonly "replaces"?: ReadonlyArray<CommonEntityRef>;
  readonly "sharesContentWith"?: ReadonlyArray<CommonEntityRef>;
}>;

export type ModuleItemsCourseUnit = Readonly<{
  readonly "id"?: CommonAbsoluteUri;
  readonly "name": CommonLocalized;
  readonly "order"?: number;
  readonly "summary"?: CommonLocalized;
  readonly "topics"?: ReadonlyArray<CommonLocalized>;
}>;

export type ModuleItemsCredit = Readonly<{
  readonly "label"?: CommonLocalized;
  readonly "system": CommonAbsoluteUri;
  readonly "value": string;
}>;

export type ModuleItemsDepartment = Readonly<Record<string, JsonValue>>;

export type ModuleItemsDuration = string | Readonly<{
  readonly "label"?: CommonLocalized;
  readonly "unit": "minutes" | "hours" | "days" | "weeks" | "months" | "years";
  readonly "value": number;
}>;

export type ModuleItemsEducationLevel = Readonly<{
  readonly "approximateAgeRange"?: ModuleItemsAgeRange;
  readonly "code": string;
  readonly "jurisdiction"?: string;
  readonly "label": CommonLocalized;
  readonly "mapping"?: ReadonlyArray<ModuleItemsEducationMapping>;
  readonly "vocabulary": CommonAbsoluteUri;
}>;

export type ModuleItemsEducationMapping = Readonly<{
  readonly "note"?: CommonLocalized;
  readonly "relationship": "exact" | "broader" | "narrower" | "approximate";
  readonly "source"?: CommonAbsoluteUri;
  readonly "target": CommonAbsoluteUri;
}>;

export type ModuleItemsEntity = Readonly<{
  readonly "contact"?: CommonEntityRef;
  readonly "description"?: CommonLocalized;
  readonly "effective"?: CommonPeriod;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "name": CommonLocalized;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "status"?: "draft" | "planned" | "active" | "suspended" | "retired" | "replaced" | "closed" | "unknown";
  readonly "type": string;
  readonly "website"?: CommonHttpsUri;
}>;

export type ModuleItemsEvent = Readonly<Record<string, JsonValue>>;

export type ModuleItemsFacility = Readonly<Record<string, JsonValue>>;

export type ModuleItemsFee = Readonly<{
  readonly "amount": string;
  readonly "basis"?: CommonLocalized;
  readonly "currency": string;
  readonly "description"?: CommonLocalized;
  readonly "effective"?: CommonPeriod;
  readonly "kind"?: "tuition" | "course" | "material" | "lab" | "equipment" | "other";
  readonly "required"?: boolean;
  readonly "waiver"?: ModuleItemsWaiver;
}>;

export type ModuleItemsGradeEligibility = Readonly<{
  readonly "display"?: CommonLocalized;
  readonly "levels"?: ReadonlyArray<string>;
  readonly "maximum"?: number;
  readonly "minimum"?: number;
}>;

export type ModuleItemsGradingResult = Readonly<{
  readonly "operator"?: "at-least" | "at-most" | "equals";
  readonly "scheme": CommonAbsoluteUri;
  readonly "value": string;
}>;

export type ModuleItemsJob = Readonly<Record<string, JsonValue>>;

export type ModuleItemsMaterial = Readonly<{
  readonly "description"?: CommonLocalized;
  readonly "href"?: CommonHttpsUri;
  readonly "id"?: CommonAbsoluteUri;
  readonly "kind"?: string;
  readonly "license"?: CommonAbsoluteUri;
  readonly "name": CommonLocalized;
  readonly "required"?: boolean;
}>;

export type ModuleItemsMealMenu = Readonly<Record<string, JsonValue>>;

export type ModuleItemsMenuItem = Readonly<{
  readonly "allergens"?: ReadonlyArray<string>;
  readonly "availability"?: ModuleItemsAvailability;
  readonly "description"?: CommonLocalized;
  readonly "dietaryLabels"?: ReadonlyArray<string>;
  readonly "id"?: CommonAbsoluteUri;
  readonly "name": CommonLocalized;
  readonly "price"?: ModuleItemsMoney;
}>;

export type ModuleItemsMenuSection = Readonly<{
  readonly "items": ReadonlyArray<ModuleItemsMenuItem>;
  readonly "name": CommonLocalized;
}>;

export type ModuleItemsMoney = Readonly<{
  readonly "amount": string;
  readonly "basis"?: CommonLocalized;
  readonly "currency": string;
}>;

export type ModuleItemsNewsItem = Readonly<Record<string, JsonValue>>;

export type ModuleItemsOffering = Readonly<{
  readonly "academicPeriod"?: CommonEntityRef;
  readonly "academicYear"?: string;
  readonly "applicationWindow"?: CommonPeriod;
  readonly "audience"?: ReadonlyArray<string>;
  readonly "availability"?: ModuleItemsAvailability;
  readonly "campuses"?: ReadonlyArray<CommonEntityRef>;
  readonly "course": CommonEntityRef;
  readonly "deliveryMode"?: string;
  readonly "end"?: CommonDate;
  readonly "enrollmentUrl"?: CommonHttpsUri;
  readonly "extensions"?: CommonExtensions;
  readonly "feeOverrides"?: ReadonlyArray<ModuleItemsFee>;
  readonly "id": CommonAbsoluteUri;
  readonly "instructors"?: ReadonlyArray<CommonEntityRef>;
  readonly "languages"?: ReadonlyArray<CommonBcp47>;
  readonly "locations"?: ReadonlyArray<CommonEntityRef>;
  readonly "modes"?: ReadonlyArray<string>;
  readonly "name": CommonLocalized;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "provider": CommonEntityRef;
  readonly "publicScheduleSummary"?: CommonLocalized;
  readonly "schedule"?: CommonLocalized;
  readonly "sections"?: ReadonlyArray<CommonEntityRef | ModuleItemsSection>;
  readonly "start"?: CommonDate;
  readonly "status"?: "planned" | "open" | "waitlist" | "full" | "closed" | "cancelled" | "unknown";
  readonly "term"?: string;
  readonly "type": "course-offering";
}>;

export type ModuleItemsOutcome = Readonly<{
  readonly "assessment"?: CommonLocalized;
  readonly "competency"?: CommonAbsoluteUri;
  readonly "id"?: CommonAbsoluteUri;
  readonly "level"?: string;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "standards"?: ReadonlyArray<CommonAbsoluteUri>;
  readonly "statement": CommonLocalized;
}>;

export type ModuleItemsPermission = Readonly<{
  readonly "contact"?: CommonEntityRef;
  readonly "display"?: CommonLocalized;
  readonly "kind": "instructor" | "department" | "program" | "counselor" | "other";
}>;

export type ModuleItemsPolicy = Readonly<{
  readonly "category"?: string;
  readonly "digest"?: string;
  readonly "documentUrl": CommonHttpsUri;
  readonly "documentVersion": string;
  readonly "effectiveDate"?: CommonDate;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "language"?: CommonBcp47;
  readonly "mediaType"?: string;
  readonly "name": CommonLocalized;
  readonly "organization"?: CommonEntityRef;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "reviewDate"?: CommonDate;
  readonly "summary"?: CommonLocalized;
  readonly "supersededBy"?: CommonEntityRef;
  readonly "supersedes"?: CommonEntityRef;
  readonly "type": "policy-document";
}>;

export type ModuleItemsPrerequisiteCourse = Readonly<{
  readonly "course": CommonEntityRef;
  readonly "display"?: CommonLocalized;
  readonly "minimumResult"?: ModuleItemsGradingResult;
}>;

export type ModuleItemsPrerequisiteExpression = ModuleItemsPrerequisiteCourse | ModuleItemsPrerequisiteLevel | ModuleItemsPrerequisitePermission | Readonly<{
  readonly "allOf": ReadonlyArray<ModuleItemsPrerequisiteExpression>;
  readonly "display"?: CommonLocalized;
}> | Readonly<{
  readonly "display"?: CommonLocalized;
  readonly "oneOf": ReadonlyArray<ModuleItemsPrerequisiteExpression>;
}> | Readonly<{
  readonly "anyOf": ReadonlyArray<ModuleItemsPrerequisiteExpression>;
  readonly "display"?: CommonLocalized;
}>;

export type ModuleItemsPrerequisiteLevel = Readonly<{
  readonly "display"?: CommonLocalized;
  readonly "educationLevel": CommonAbsoluteUri;
}>;

export type ModuleItemsPrerequisitePermission = Readonly<{
  readonly "display"?: CommonLocalized;
  readonly "permission": ModuleItemsPermission;
}>;

export type ModuleItemsProgram = Readonly<Record<string, JsonValue>>;

export type ModuleItemsRepeatability = Readonly<{
  readonly "maximumAttempts"?: number;
  readonly "note"?: CommonLocalized;
  readonly "repeatable": boolean;
}>;

export type ModuleItemsRequirementGroup = Readonly<{
  readonly "condition"?: CommonLocalized;
  readonly "courses"?: ReadonlyArray<CommonEntityRef>;
  readonly "credits"?: ModuleItemsCredit;
  readonly "display"?: CommonLocalized;
  readonly "externalCredential"?: CommonEntityRef;
  readonly "kind": "all" | "choose" | "minimum-credits" | "one-of" | "conditional" | "optional" | "recommended" | "external-credential";
  readonly "label"?: CommonLocalized;
  readonly "minimum"?: number;
  readonly "requirements"?: ReadonlyArray<ModuleItemsRequirementGroup>;
}>;

export type ModuleItemsRoleContact = Readonly<{
  readonly "department"?: CommonEntityRef;
  readonly "email"?: string;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "languages"?: ReadonlyArray<CommonBcp47>;
  readonly "organization"?: CommonEntityRef;
  readonly "publicationReview"?: Readonly<Record<string, JsonValue>>;
  readonly "role": CommonLocalized;
  readonly "telephone"?: string;
  readonly "type": "role-contact";
  readonly "website"?: CommonHttpsUri;
}>;

export type ModuleItemsSection = Readonly<{
  readonly "availability"?: ModuleItemsAvailability;
  readonly "capacity"?: number;
  readonly "deliveryMode"?: string;
  readonly "end"?: CommonDate;
  readonly "id": CommonAbsoluteUri;
  readonly "instructor"?: CommonEntityRef;
  readonly "location"?: CommonEntityRef;
  readonly "name"?: CommonLocalized;
  readonly "offering": CommonEntityRef;
  readonly "publicSectionCode": string;
  readonly "schedule"?: CommonLocalized;
  readonly "start"?: CommonDate;
  readonly "status"?: "planned" | "open" | "full" | "closed" | "cancelled" | "unknown";
  readonly "type": "course-section";
}>;

export type ModuleItemsService = Readonly<Record<string, JsonValue>>;

export type ModuleItemsSportsTeam = Readonly<Record<string, JsonValue>>;

export type ModuleItemsStaff = Readonly<{
  readonly "departments"?: ReadonlyArray<CommonEntityRef>;
  readonly "effective"?: CommonPeriod;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "institutionalEmail"?: string;
  readonly "institutionalTelephone"?: string;
  readonly "jobTitles"?: ReadonlyArray<CommonLocalized>;
  readonly "languages"?: ReadonlyArray<CommonBcp47>;
  readonly "name": CommonLocalized;
  readonly "profileUrl"?: CommonHttpsUri;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "publicCourses"?: ReadonlyArray<CommonEntityRef>;
  readonly "publicationReview": Readonly<{
  readonly "expires"?: CommonDateTime;
  readonly "reviewedAt": CommonDateTime;
  readonly "reviewedBy"?: CommonEntityRef;
  readonly "status": "approved" | "pending" | "withdrawn" | "expired";
}>;
  readonly "teams"?: ReadonlyArray<CommonEntityRef>;
  readonly "type": "staff-member";
}>;

export type ModuleItemsStage = Readonly<{
  readonly "choose"?: ModuleItemsRequirementGroup;
  readonly "courses"?: ReadonlyArray<CommonEntityRef>;
  readonly "order": number;
}>;

export type ModuleItemsStandardAlignment = Readonly<{
  readonly "alignment"?: "exact" | "partial" | "broad";
  readonly "alignmentType"?: "exact" | "partial" | "broad";
  readonly "effectiveVersion"?: string;
  readonly "framework": CommonAbsoluteUri;
  readonly "item": CommonAbsoluteUri;
  readonly "source"?: CommonAbsoluteUri;
}>;

export type ModuleItemsStatistic = Readonly<{
  readonly "confidence"?: number;
  readonly "dimensions"?: Readonly<Record<string, JsonValue>>;
  readonly "extensions"?: CommonExtensions;
  readonly "id": CommonAbsoluteUri;
  readonly "methodology"?: CommonHttpsUri;
  readonly "metric": CommonAbsoluteUri;
  readonly "observedAt": CommonDateTime;
  readonly "period"?: CommonPeriod;
  readonly "provenance"?: ReadonlyArray<Provenance>;
  readonly "publishedAt"?: CommonDateTime;
  readonly "revision"?: string;
  readonly "source": CommonAbsoluteUri;
  readonly "subject": CommonEntityRef;
  readonly "suppression"?: ModuleItemsSuppression;
  readonly "type": "statistic";
  readonly "unit"?: CommonAbsoluteUri;
  readonly "value"?: JsonValue;
}>;

export type ModuleItemsSuppression = Readonly<{
  readonly "policy"?: CommonHttpsUri;
  readonly "suppressed": true;
  readonly "suppressionReason": string;
}>;

export type ModuleItemsTransportService = Readonly<Record<string, JsonValue>>;

export type ModuleItemsWaiver = Readonly<{
  readonly "available": boolean;
  readonly "contact"?: CommonEntityRef;
  readonly "description"?: CommonLocalized;
  readonly "url"?: CommonHttpsUri;
}>;

export type ModuleItemsWorkload = Readonly<{
  readonly "contactHours"?: number;
  readonly "independentHours"?: number;
  readonly "label"?: CommonLocalized;
  readonly "totalHours"?: number;
  readonly "unit"?: "per-week" | "per-term" | "per-course";
}>;

export type ModuleItems = JsonValue;

export type ModulesCampusCatalog = JsonValue;

export type ModulesDepartmentCatalog = JsonValue;

export type ModulesStaffDirectory = JsonValue;

export type ModulesCourseCatalog = JsonValue;

export type ModulesCourseOfferingCatalog = JsonValue;

export type ModulesProgramCatalog = JsonValue;

export type ModulesAcademicCalendar = JsonValue;

export type ModulesEventCatalog = JsonValue;

export type ModulesFacilityCatalog = JsonValue;

export type ModulesServiceCatalog = JsonValue;

export type ModulesPolicyCatalog = JsonValue;

export type ModulesAdmissionsProfile = JsonValue;

export type ModulesSportsCatalog = JsonValue;

export type ModulesTransportationCatalog = JsonValue;

export type ModulesMealMenuCatalog = JsonValue;

export type ModulesClubCatalog = JsonValue;

export type ModulesJobCatalog = JsonValue;

export type ModulesNewsFeed = JsonValue;

export type ModulesStatisticsProfile = JsonValue;

export type ModulesApiReference = JsonValue;
