import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readAllSchemas, SCHEMA_FILES } from '@paperandslate/eom-schema';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const output = join(root, 'docs', 'reference', 'schema-catalog.md');

function requiredFields(schema: Record<string, unknown>): readonly string[] {
  return Array.isArray(schema.required)
    ? schema.required.filter((value): value is string => typeof value === 'string')
    : [];
}

function propertyNames(schema: Record<string, unknown>): readonly string[] {
  if (
    typeof schema.properties !== 'object' ||
    schema.properties === null ||
    Array.isArray(schema.properties)
  )
    return [];
  return Object.keys(schema.properties).sort(compareStrings);
}

function compareStrings(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

const lines = [
  '<!-- @generated by scripts/generate-schema-docs.ts; do not edit directly. -->',
  '',
  '# EOM 1.0 Schema Catalog',
  '',
  'This page is generated from the JSON Schema 2020-12 source files under `schemas/1.0/`.',
  '',
  '| Resource type | Schema | Required fields | Top-level fields |',
  '| --- | --- | --- | --- |',
];
const schemas = readAllSchemas();
SCHEMA_FILES.filter((file) => file !== 'common.schema.json').forEach((file) => {
  const schema = schemas.find(
    (candidate) => candidate.$id === `https://paperandslate.org/schemas/eom/1.0/${file}`,
  );
  if (!schema) return;
  const type = file.replace('.schema.json', '');
  const required = requiredFields(schema);
  const properties = propertyNames(schema);
  lines.push(
    `| \`${type}\` | [${file}](../../schemas/1.0/${file}) | ${required.map((value) => `\`${value}\``).join(', ') || '—'} | ${properties.map((value) => `\`${value}\``).join(', ') || '—'} |`,
  );
});
lines.push(
  '',
  'The catalog is descriptive. The versioned schema files are authoritative for validation.',
  '',
);
const generated = lines.join('\n');
if (process.argv.includes('--check')) {
  let existing: string;
  try {
    existing = await readFile(output, 'utf8');
  } catch {
    throw new Error(
      `Generated schema documentation is missing at ${output}. Run pnpm generate:docs.`,
    );
  }
  if (existing !== generated) {
    throw new Error(
      `Generated schema documentation is stale at ${output}. Run pnpm generate:docs.`,
    );
  }
  process.stdout.write(`generated schema documentation is current: ${output}\n`);
} else {
  await mkdir(dirname(output), { recursive: true });
  await writeFile(output, generated, 'utf8');
  process.stdout.write(`generated ${output}\n`);
}
